import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

final appTheme=FlexThemeData.light(
  colors: const FlexSchemeColor(
    primary: Color(0xff220804),
    // primaryVariant: Color(0xff917138),
    secondary: Color(0xffeeac29),
    // secondaryVariant: Color(0xfff5e9c9),
    appBarColor: Color(0xfff5e9c9),
    error: Color(0xffb00020),
  ),
  surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
  blendLevel: 14,
  appBarStyle: FlexAppBarStyle.primary,
  appBarOpacity: 0.87,
  appBarElevation: 1,
  transparentStatusBar: true,
  tabBarStyle: FlexTabBarStyle.forBackground,
  tooltipsMatchBackground: true,
  swapColors: false,
  lightIsWhite: true,
  // useSubThemes: true,
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  // To use playground font, add GoogleFonts package and uncomment:
  // fontFamily: GoogleFonts.notoSans().fontFamily,
  subThemesData: const FlexSubThemesData(
    useTextTheme: true,
    fabUseShape: true,
    interactionEffects: true,
    tabBarIndicatorSchemeColor: SchemeColor.primary,
    bottomNavigationBarElevation: 0,
    bottomNavigationBarOpacity: 0.95,
    navigationBarOpacity: 0.95,
    // navigationBarMutedUnselectedText: true,
    navigationBarMutedUnselectedIcon: true,
    inputDecoratorIsFilled: true,
    inputDecoratorBorderType: FlexInputBorderType.outline,
    inputDecoratorUnfocusedHasBorder: true,
    blendOnColors: true,
    blendTextTheme: true,
    popupMenuOpacity: 0.95,
  ),
);
final appDarkTheme = FlexThemeData.dark(
  colors: const FlexSchemeColor(
    primary: Color(0xff8d7f7d),
    // primaryVariant: Color(0xffc3b59d),
    secondary: Color(0xffeed6a6),
    // secondaryVariant: Color(0xfff8ecd4),
    appBarColor: Color(0xfff8ecd4),
    error: Color(0xffcf6679),
  ),
  surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
  blendLevel: 14,
  appBarStyle: FlexAppBarStyle.background,
  appBarOpacity: 0.87,
  appBarElevation: 1,
  transparentStatusBar: true,
  tabBarStyle: FlexTabBarStyle.forBackground,
  tooltipsMatchBackground: true,
  swapColors: false,
  darkIsTrueBlack: false,
  // useSubThemes: true,
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  // To use playground font, add GoogleFonts package and uncomment:
  // fontFamily: GoogleFonts.notoSans().fontFamily,
  subThemesData: const FlexSubThemesData(
    useTextTheme: true,
    fabUseShape: true,
    interactionEffects: true,
    tabBarIndicatorSchemeColor: SchemeColor.primary,
    bottomNavigationBarElevation: 0,
    bottomNavigationBarOpacity: 0.95,
    navigationBarOpacity: 0.95,
    // navigationBarMutedUnselectedText: true,
    navigationBarMutedUnselectedIcon: true,
    inputDecoratorIsFilled: true,
    inputDecoratorBorderType: FlexInputBorderType.outline,
    inputDecoratorUnfocusedHasBorder: true,
    blendOnColors: true,
    blendTextTheme: true,
    popupMenuOpacity: 0.95,
  ),
);
// If you do not have a themeMode switch, uncomment this line
// to let the device system mode control the theme mode:
// themeMode: ThemeMode.system,
